import pandas as pd
import fastf1
#-----------------------------------------------------------------------------------------------------------------------
#timing_data_RaceName_index =
# [HAM, RUS, VER, PER, LEC, SAI, NOR, RIC, ALO, OCO,
# GAS, TSU, VET, STR, BOT, ZHO, ALB, LAT, MAG, MSC]
#-----------------------------------------------------------------------------------------------------------------------
timing_app_data_BH = [[[] for i in range(5)]for j in range(20)]
timing_app_data_SA = [[[] for i in range(5)]for j in range(20)]
timing_app_data_AU = [[[] for i in range(5)]for j in range(20)]
#-----------------------------------------------------------------------------------------------------------------------
#importing the data for each session of all races
#the naming rule follow the rule below:
#the race code as the two-letter country code and the session
fastf1.Cache.enable_cache("C:\Python\project4")
BH_FP1 = fastf1.get_session(2022, 1, "FP1")
BH_FP2 = fastf1.get_session(2022, 1, "FP2")
BH_FP3 = fastf1.get_session(2022, 1, "FP3")
BH_Q = fastf1.get_session(2022, 1, "Q")
BH_R = fastf1.get_session(2022, 1, "R")
#-----------------------------------------------------------------------------------------------------------------------
SA_FP1 = fastf1.get_session(2022, 2, "FP1")
SA_FP2 = fastf1.get_session(2022, 2, "FP2")
SA_FP3 = fastf1.get_session(2022, 2, "FP3")
SA_Q = fastf1.get_session(2022, 2, "Q")
SA_R = fastf1.get_session(2022, 2, "R")
#-----------------------------------------------------------------------------------------------------------------------
AU_FP1 = fastf1.get_session(2022, 3, "FP1")
AU_FP2 = fastf1.get_session(2022, 3, "FP2")
AU_FP3 = fastf1.get_session(2022, 3, "FP3")
AU_Q = fastf1.get_session(2022, 3, "Q")
AU_R = fastf1.get_session(2022, 3, "R")
#-----------------------------------------------------------------------------------------------------------------------
timing_app_data_BH_FP1 = fastf1.api.timing_app_data(BH_FP1.api_path, response=None, livedata=None)
timing_app_data_BH_FP2 = fastf1.api.timing_app_data(BH_FP2.api_path, response=None, livedata=None)
timing_app_data_BH_FP3 = fastf1.api.timing_app_data(BH_FP3.api_path, response=None, livedata=None)
timing_app_data_BH_Q = fastf1.api.timing_app_data(BH_Q.api_path, response=None, livedata=None)
timing_app_data_BH_R = fastf1.api.timing_app_data(BH_R.api_path, response=None, livedata=None)
#-----------------------------------------------------------------------------------------------------------------------
timing_app_data_SA_FP1 = fastf1.api.timing_app_data(SA_FP1.api_path, response=None, livedata=None)
timing_app_data_SA_FP2 = fastf1.api.timing_app_data(SA_FP2.api_path, response=None, livedata=None)
timing_app_data_SA_FP3 = fastf1.api.timing_app_data(SA_FP3.api_path, response=None, livedata=None)
timing_app_data_SA_Q = fastf1.api.timing_app_data(SA_Q.api_path, response=None, livedata=None)
timing_app_data_SA_R = fastf1.api.timing_app_data(SA_R.api_path, response=None, livedata=None)
#-----------------------------------------------------------------------------------------------------------------------
timing_app_data_AU_FP1 = fastf1.api.timing_app_data(AU_FP1.api_path, response=None, livedata=None)
timing_app_data_AU_FP2 = fastf1.api.timing_app_data(AU_FP2.api_path, response=None, livedata=None)
timing_app_data_AU_FP3 = fastf1.api.timing_app_data(AU_FP3.api_path, response=None, livedata=None)
timing_app_data_AU_Q = fastf1.api.timing_app_data(AU_Q.api_path, response=None, livedata=None)
timing_app_data_AU_R = fastf1.api.timing_app_data(AU_R.api_path, response=None, livedata=None)
#-----------------------------------------------------------------------------------------------------------------------
def Timing_app_data_BH():
    grouped_timing_data_BH_FP1_0 = timing_app_data_BH_FP1.groupby(timing_app_data_BH_FP1.Driver)
    timing_app_data_BH[0][0] = grouped_timing_data_BH_FP1_0.get_group("44")
    timing_app_data_BH[1][0] = grouped_timing_data_BH_FP1_0.get_group("63")
    timing_app_data_BH[2][0] = grouped_timing_data_BH_FP1_0.get_group("1")
    timing_app_data_BH[3][0] = grouped_timing_data_BH_FP1_0.get_group("11")
    timing_app_data_BH[4][0] = grouped_timing_data_BH_FP1_0.get_group("16")
    timing_app_data_BH[5][0] = grouped_timing_data_BH_FP1_0.get_group("55")
    timing_app_data_BH[6][0] = grouped_timing_data_BH_FP1_0.get_group("3")
    timing_app_data_BH[7][0] = grouped_timing_data_BH_FP1_0.get_group("4")
    timing_app_data_BH[8][0] = grouped_timing_data_BH_FP1_0.get_group("14")
    timing_app_data_BH[9][0] = grouped_timing_data_BH_FP1_0.get_group("31")
    timing_app_data_BH[10][0] = grouped_timing_data_BH_FP1_0.get_group("10")
    timing_app_data_BH[11][0] = grouped_timing_data_BH_FP1_0.get_group("22")
    # VET[0] = grouped_timing_data_BH_FP1_0.get_group("5")
    timing_app_data_BH[12][0] = grouped_timing_data_BH_FP1_0.get_group("27")
    timing_app_data_BH[13][0] = grouped_timing_data_BH_FP1_0.get_group("18")
    timing_app_data_BH[14][0] = grouped_timing_data_BH_FP1_0.get_group("77")
    timing_app_data_BH[15][0] = grouped_timing_data_BH_FP1_0.get_group("24")
    timing_app_data_BH[16][0] = grouped_timing_data_BH_FP1_0.get_group("23")
    timing_app_data_BH[17][0] = grouped_timing_data_BH_FP1_0.get_group("6")
    timing_app_data_BH[18][0] = grouped_timing_data_BH_FP1_0.get_group("20")
    timing_app_data_BH[19][0] = grouped_timing_data_BH_FP1_0.get_group("47")

    grouped_timing_data_BH_FP2_0 = timing_app_data_BH_FP2.groupby(timing_app_data_BH_FP2.Driver)
    timing_app_data_BH[0][1] = grouped_timing_data_BH_FP2_0.get_group("44")
    timing_app_data_BH[1][1] = grouped_timing_data_BH_FP2_0.get_group("63")
    timing_app_data_BH[2][1] = grouped_timing_data_BH_FP2_0.get_group("1")
    timing_app_data_BH[3][1] = grouped_timing_data_BH_FP2_0.get_group("11")
    timing_app_data_BH[4][1] = grouped_timing_data_BH_FP2_0.get_group("16")
    timing_app_data_BH[5][1] = grouped_timing_data_BH_FP2_0.get_group("55")
    timing_app_data_BH[6][1] = grouped_timing_data_BH_FP2_0.get_group("3")
    timing_app_data_BH[7][1] = grouped_timing_data_BH_FP2_0.get_group("4")
    timing_app_data_BH[8][1] = grouped_timing_data_BH_FP2_0.get_group("14")
    timing_app_data_BH[9][1] = grouped_timing_data_BH_FP2_0.get_group("31")
    timing_app_data_BH[10][1] = grouped_timing_data_BH_FP2_0.get_group("10")
    timing_app_data_BH[11][1] = grouped_timing_data_BH_FP2_0.get_group("22")
    # VET[0] = grouped_timing_data_BH_F1_0.get_group("5")
    timing_app_data_BH[12][1] = grouped_timing_data_BH_FP2_0.get_group("27")
    timing_app_data_BH[13][1] = grouped_timing_data_BH_FP2_0.get_group("18")
    timing_app_data_BH[14][1] = grouped_timing_data_BH_FP2_0.get_group("77")
    timing_app_data_BH[15][1] = grouped_timing_data_BH_FP2_0.get_group("24")
    timing_app_data_BH[16][1] = grouped_timing_data_BH_FP2_0.get_group("23")
    timing_app_data_BH[17][1] = grouped_timing_data_BH_FP2_0.get_group("6")
    timing_app_data_BH[18][1] = grouped_timing_data_BH_FP2_0.get_group("20")
    timing_app_data_BH[19][1] = grouped_timing_data_BH_FP2_0.get_group("47")

    grouped_timing_data_BH_FP3_0 = timing_app_data_BH_FP3.groupby(timing_app_data_BH_FP3.Driver)
    timing_app_data_BH[0][2] = grouped_timing_data_BH_FP3_0.get_group("44")
    timing_app_data_BH[1][2] = grouped_timing_data_BH_FP3_0.get_group("63")
    timing_app_data_BH[2][2] = grouped_timing_data_BH_FP3_0.get_group("1")
    timing_app_data_BH[3][2] = grouped_timing_data_BH_FP3_0.get_group("11")
    timing_app_data_BH[4][2] = grouped_timing_data_BH_FP3_0.get_group("16")
    timing_app_data_BH[5][2] = grouped_timing_data_BH_FP3_0.get_group("55")
    timing_app_data_BH[6][2] = grouped_timing_data_BH_FP3_0.get_group("3")
    timing_app_data_BH[7][2] = grouped_timing_data_BH_FP3_0.get_group("4")
    timing_app_data_BH[8][2] = grouped_timing_data_BH_FP3_0.get_group("14")
    timing_app_data_BH[9][2] = grouped_timing_data_BH_FP3_0.get_group("31")
    timing_app_data_BH[10][2] = grouped_timing_data_BH_FP3_0.get_group("10")
    timing_app_data_BH[11][2] = pd.DataFrame({'condition': ["DNS"]})
    # VET[0] = grouped_timing_data_BH_F1_0.get_group("5")
    timing_app_data_BH[12][2] = grouped_timing_data_BH_FP3_0.get_group("27")
    timing_app_data_BH[13][2] = grouped_timing_data_BH_FP3_0.get_group("18")
    timing_app_data_BH[14][2] = grouped_timing_data_BH_FP3_0.get_group("77")
    timing_app_data_BH[15][2] = grouped_timing_data_BH_FP3_0.get_group("24")
    timing_app_data_BH[16][2] = grouped_timing_data_BH_FP3_0.get_group("23")
    timing_app_data_BH[17][2] = grouped_timing_data_BH_FP3_0.get_group("6")
    timing_app_data_BH[18][2] = grouped_timing_data_BH_FP3_0.get_group("20")
    timing_app_data_BH[19][2] = grouped_timing_data_BH_FP3_0.get_group("47")

    grouped_timing_data_BH_Q_0 = timing_app_data_BH_Q.groupby(timing_app_data_BH_Q.Driver)
    timing_app_data_BH[0][3] = grouped_timing_data_BH_Q_0.get_group("44")
    timing_app_data_BH[1][3] = grouped_timing_data_BH_Q_0.get_group("63")
    timing_app_data_BH[2][3] = grouped_timing_data_BH_Q_0.get_group("1")
    timing_app_data_BH[3][3] = grouped_timing_data_BH_Q_0.get_group("11")
    timing_app_data_BH[4][3] = grouped_timing_data_BH_Q_0.get_group("16")
    timing_app_data_BH[5][3] = grouped_timing_data_BH_Q_0.get_group("55")
    timing_app_data_BH[6][3] = grouped_timing_data_BH_Q_0.get_group("3")
    timing_app_data_BH[7][3] = grouped_timing_data_BH_Q_0.get_group("4")
    timing_app_data_BH[8][3] = grouped_timing_data_BH_Q_0.get_group("14")
    timing_app_data_BH[9][3] = grouped_timing_data_BH_Q_0.get_group("31")
    timing_app_data_BH[10][3] = grouped_timing_data_BH_Q_0.get_group("10")
    timing_app_data_BH[11][3] = grouped_timing_data_BH_Q_0.get_group("22")
    # VET[0] = grouped_timing_data_BH_F1_0.get_group("5")
    timing_app_data_BH[12][3] = grouped_timing_data_BH_Q_0.get_group("27")
    timing_app_data_BH[13][3] = grouped_timing_data_BH_Q_0.get_group("18")
    timing_app_data_BH[14][3] = grouped_timing_data_BH_Q_0.get_group("77")
    timing_app_data_BH[15][3] = grouped_timing_data_BH_Q_0.get_group("24")
    timing_app_data_BH[16][3] = grouped_timing_data_BH_Q_0.get_group("23")
    timing_app_data_BH[17][3] = grouped_timing_data_BH_Q_0.get_group("6")
    timing_app_data_BH[18][3] = grouped_timing_data_BH_Q_0.get_group("20")
    timing_app_data_BH[19][3] = grouped_timing_data_BH_Q_0.get_group("47")

    grouped_timing_data_BH_R_0 = timing_app_data_BH_R.groupby(timing_app_data_BH_R.Driver)
    timing_app_data_BH[0][4] = grouped_timing_data_BH_R_0.get_group("44")
    timing_app_data_BH[1][4] = grouped_timing_data_BH_R_0.get_group("63")
    timing_app_data_BH[2][4] = grouped_timing_data_BH_R_0.get_group("1")
    timing_app_data_BH[3][4] = grouped_timing_data_BH_R_0.get_group("11")
    timing_app_data_BH[4][4] = grouped_timing_data_BH_R_0.get_group("16")
    timing_app_data_BH[5][4] = grouped_timing_data_BH_R_0.get_group("55")
    timing_app_data_BH[6][4] = grouped_timing_data_BH_R_0.get_group("3")
    timing_app_data_BH[7][4] = grouped_timing_data_BH_R_0.get_group("4")
    timing_app_data_BH[8][4] = grouped_timing_data_BH_R_0.get_group("14")
    timing_app_data_BH[9][4] = grouped_timing_data_BH_R_0.get_group("31")
    timing_app_data_BH[10][4] = grouped_timing_data_BH_R_0.get_group("10")
    timing_app_data_BH[11][4] = grouped_timing_data_BH_R_0.get_group("22")
    # VET[0] = grouped_timing_data_BH_F1_0.get_group("5")
    timing_app_data_BH[12][4] = grouped_timing_data_BH_R_0.get_group("27")
    timing_app_data_BH[13][4] = grouped_timing_data_BH_R_0.get_group("18")
    timing_app_data_BH[14][4] = grouped_timing_data_BH_R_0.get_group("77")
    timing_app_data_BH[15][4] = grouped_timing_data_BH_R_0.get_group("24")
    timing_app_data_BH[16][4] = grouped_timing_data_BH_R_0.get_group("23")
    timing_app_data_BH[17][4] = grouped_timing_data_BH_R_0.get_group("6")
    timing_app_data_BH[18][4] = grouped_timing_data_BH_R_0.get_group("20")
    timing_app_data_BH[19][4] = grouped_timing_data_BH_R_0.get_group("47")
    return

def Timing_app_data_BH_Writer():
    i = 0
    timing_app_data_BH[0][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP1_44')
    timing_app_data_BH[1][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP1_63')
    timing_app_data_BH[2][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP1_1')
    timing_app_data_BH[3][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP1_11')
    timing_app_data_BH[4][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP1_16')
    timing_app_data_BH[5][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP1_55')
    timing_app_data_BH[6][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP1_4')
    timing_app_data_BH[7][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP1_3')
    timing_app_data_BH[8][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP1_14')
    timing_app_data_BH[9][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP1_31')
    timing_app_data_BH[10][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP1_10')
    timing_app_data_BH[11][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP1_22')
    timing_app_data_BH[12][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP1_5')
    timing_app_data_BH[13][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP1_18')
    timing_app_data_BH[14][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP1_77')
    timing_app_data_BH[15][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP1_24')
    timing_app_data_BH[16][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP1_23')
    timing_app_data_BH[17][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP1_6')
    timing_app_data_BH[18][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP1_20')
    timing_app_data_BH[19][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP1_47')

    i = 1
    timing_app_data_BH[0][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP2_44')
    timing_app_data_BH[1][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP2_63')
    timing_app_data_BH[2][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP2_1')
    timing_app_data_BH[3][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP2_11')
    timing_app_data_BH[4][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP2_16')
    timing_app_data_BH[5][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP2_55')
    timing_app_data_BH[6][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP2_4')
    timing_app_data_BH[7][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP2_3')
    timing_app_data_BH[8][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP2_14')
    timing_app_data_BH[9][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP2_31')
    timing_app_data_BH[10][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP2_10')
    timing_app_data_BH[11][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP2_22')
    timing_app_data_BH[12][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP2_5')
    timing_app_data_BH[13][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP2_18')
    timing_app_data_BH[14][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP2_77')
    timing_app_data_BH[15][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP2_24')
    timing_app_data_BH[16][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP2_23')
    timing_app_data_BH[17][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP2_6')
    timing_app_data_BH[18][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP2_20')
    timing_app_data_BH[19][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP2_47')

    i = 2
    timing_app_data_BH[0][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP3_44')
    timing_app_data_BH[1][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP3_63')
    timing_app_data_BH[2][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP3_1')
    timing_app_data_BH[3][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP3_11')
    timing_app_data_BH[4][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP3_16')
    timing_app_data_BH[5][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP3_55')
    timing_app_data_BH[6][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP3_4')
    timing_app_data_BH[7][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP3_3')
    timing_app_data_BH[8][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP3_14')
    timing_app_data_BH[9][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP3_31')
    timing_app_data_BH[10][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP3_10')
    timing_app_data_BH[11][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP3_22')
    timing_app_data_BH[12][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP3_5')
    timing_app_data_BH[13][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP3_18')
    timing_app_data_BH[14][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP3_77')
    timing_app_data_BH[15][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP3_24')
    timing_app_data_BH[16][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP3_23')
    timing_app_data_BH[17][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP3_6')
    timing_app_data_BH[18][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP3_20')
    timing_app_data_BH[19][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_FP3_47')

    i = 3
    timing_app_data_BH[0][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_Q_44')
    timing_app_data_BH[1][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_Q_63')
    timing_app_data_BH[2][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_Q_1')
    timing_app_data_BH[3][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_Q_11')
    timing_app_data_BH[4][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_Q_16')
    timing_app_data_BH[5][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_Q_55')
    timing_app_data_BH[6][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_Q_4')
    timing_app_data_BH[7][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_Q_3')
    timing_app_data_BH[8][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_Q_14')
    timing_app_data_BH[9][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_Q_31')
    timing_app_data_BH[10][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_Q_10')
    timing_app_data_BH[11][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_Q_22')
    timing_app_data_BH[12][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_Q_5')
    timing_app_data_BH[13][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_Q_18')
    timing_app_data_BH[14][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_Q_77')
    timing_app_data_BH[15][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_Q_24')
    timing_app_data_BH[16][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_Q_23')
    timing_app_data_BH[17][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_Q_6')
    timing_app_data_BH[18][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_Q_20')
    timing_app_data_BH[19][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_Q_47')

    i = 4
    timing_app_data_BH[0][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_R_44')
    timing_app_data_BH[1][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_R_63')
    timing_app_data_BH[2][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_R_1')
    timing_app_data_BH[3][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_R_11')
    timing_app_data_BH[4][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_R_16')
    timing_app_data_BH[5][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_R_55')
    timing_app_data_BH[6][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_R_4')
    timing_app_data_BH[7][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_R_3')
    timing_app_data_BH[8][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_R_14')
    timing_app_data_BH[9][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_R_31')
    timing_app_data_BH[10][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_R_10')
    timing_app_data_BH[11][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_R_22')
    timing_app_data_BH[12][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_R_5')
    timing_app_data_BH[13][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_R_18')
    timing_app_data_BH[14][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_R_77')
    timing_app_data_BH[15][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_R_24')
    timing_app_data_BH[16][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_R_23')
    timing_app_data_BH[17][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_R_6')
    timing_app_data_BH[18][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_R_20')
    timing_app_data_BH[19][i].to_csv(r'D:\project4_data\BH\timing_app_data_BH_R_47')
    return
#-----------------------------------------------------------------------------------------------------------------------
def Timing_app_data_SA():
    grouped_timing_data_BH_FP1_0 = timing_app_data_SA_FP1.groupby(timing_app_data_SA_FP1.Driver)
    timing_app_data_SA[0][0] = grouped_timing_data_BH_FP1_0.get_group("44")
    timing_app_data_SA[1][0] = grouped_timing_data_BH_FP1_0.get_group("63")
    timing_app_data_SA[2][0] = grouped_timing_data_BH_FP1_0.get_group("1")
    timing_app_data_SA[3][0] = grouped_timing_data_BH_FP1_0.get_group("11")
    timing_app_data_SA[4][0] = grouped_timing_data_BH_FP1_0.get_group("16")
    timing_app_data_SA[5][0] = grouped_timing_data_BH_FP1_0.get_group("55")
    timing_app_data_SA[6][0] = grouped_timing_data_BH_FP1_0.get_group("3")
    timing_app_data_SA[7][0] = grouped_timing_data_BH_FP1_0.get_group("4")
    timing_app_data_SA[8][0] = grouped_timing_data_BH_FP1_0.get_group("14")
    timing_app_data_SA[9][0] = grouped_timing_data_BH_FP1_0.get_group("31")
    timing_app_data_SA[10][0] = grouped_timing_data_BH_FP1_0.get_group("10")
    timing_app_data_SA[11][0] = grouped_timing_data_BH_FP1_0.get_group("22")
    # VET[0] = grouped_timing_data_BH_FP1_0.get_group("5")
    timing_app_data_SA[12][0] = grouped_timing_data_BH_FP1_0.get_group("27")
    timing_app_data_SA[13][0] = grouped_timing_data_BH_FP1_0.get_group("18")
    timing_app_data_SA[14][0] = grouped_timing_data_BH_FP1_0.get_group("77")
    timing_app_data_SA[15][0] = grouped_timing_data_BH_FP1_0.get_group("24")
    timing_app_data_SA[16][0] = grouped_timing_data_BH_FP1_0.get_group("23")
    timing_app_data_SA[17][0] = grouped_timing_data_BH_FP1_0.get_group("6")
    timing_app_data_SA[18][0] = grouped_timing_data_BH_FP1_0.get_group("20")
    timing_app_data_SA[19][0] = grouped_timing_data_BH_FP1_0.get_group("47")

    grouped_timing_data_BH_FP2_0 = timing_app_data_SA_FP2.groupby(timing_app_data_SA_FP2.Driver)
    timing_app_data_SA[0][1] = grouped_timing_data_BH_FP2_0.get_group("44")
    timing_app_data_SA[1][1] = grouped_timing_data_BH_FP2_0.get_group("63")
    timing_app_data_SA[2][1] = grouped_timing_data_BH_FP2_0.get_group("1")
    timing_app_data_SA[3][1] = grouped_timing_data_BH_FP2_0.get_group("11")
    timing_app_data_SA[4][1] = grouped_timing_data_BH_FP2_0.get_group("16")
    timing_app_data_SA[5][1] = grouped_timing_data_BH_FP2_0.get_group("55")
    timing_app_data_SA[6][1] = grouped_timing_data_BH_FP2_0.get_group("3")
    timing_app_data_SA[7][1] = grouped_timing_data_BH_FP2_0.get_group("4")
    timing_app_data_SA[8][1] = grouped_timing_data_BH_FP2_0.get_group("14")
    timing_app_data_SA[9][1] = grouped_timing_data_BH_FP2_0.get_group("31")
    timing_app_data_SA[10][1] = grouped_timing_data_BH_FP2_0.get_group("10")
    timing_app_data_SA[11][1] = grouped_timing_data_BH_FP2_0.get_group("22")
    # VET[0] = grouped_timing_data_BH_F1_0.get_group("5")
    timing_app_data_SA[12][1] = grouped_timing_data_BH_FP2_0.get_group("27")
    timing_app_data_SA[13][1] = grouped_timing_data_BH_FP2_0.get_group("18")
    timing_app_data_SA[14][1] = grouped_timing_data_BH_FP2_0.get_group("77")
    timing_app_data_SA[15][1] = grouped_timing_data_BH_FP2_0.get_group("24")
    timing_app_data_SA[16][1] = grouped_timing_data_BH_FP2_0.get_group("23")
    timing_app_data_SA[17][1] = grouped_timing_data_BH_FP2_0.get_group("6")
    timing_app_data_SA[18][1] = grouped_timing_data_BH_FP2_0.get_group("20")
    timing_app_data_SA[19][1] = grouped_timing_data_BH_FP2_0.get_group("47")

    grouped_timing_data_BH_FP3_0 = timing_app_data_SA_FP3.groupby(timing_app_data_SA_FP3.Driver)
    timing_app_data_SA[0][2] = grouped_timing_data_BH_FP3_0.get_group("44")
    timing_app_data_SA[1][2] = grouped_timing_data_BH_FP3_0.get_group("63")
    timing_app_data_SA[2][2] = grouped_timing_data_BH_FP3_0.get_group("1")
    timing_app_data_SA[3][2] = grouped_timing_data_BH_FP3_0.get_group("11")
    timing_app_data_SA[4][2] = grouped_timing_data_BH_FP3_0.get_group("16")
    timing_app_data_SA[5][2] = grouped_timing_data_BH_FP3_0.get_group("55")
    timing_app_data_SA[6][2] = grouped_timing_data_BH_FP3_0.get_group("3")
    timing_app_data_SA[7][2] = grouped_timing_data_BH_FP3_0.get_group("4")
    timing_app_data_SA[8][2] = grouped_timing_data_BH_FP3_0.get_group("14")
    timing_app_data_SA[9][2] = grouped_timing_data_BH_FP3_0.get_group("31")
    timing_app_data_SA[10][2] = grouped_timing_data_BH_FP3_0.get_group("10")
    timing_app_data_SA[11][2] = pd.DataFrame({'condition': ["DNS"]})
    # VET[0] = grouped_timing_data_BH_F1_0.get_group("5")
    timing_app_data_SA[12][2] = grouped_timing_data_BH_FP3_0.get_group("27")
    timing_app_data_SA[13][2] = grouped_timing_data_BH_FP3_0.get_group("18")
    timing_app_data_SA[14][2] = grouped_timing_data_BH_FP3_0.get_group("77")
    timing_app_data_SA[15][2] = grouped_timing_data_BH_FP3_0.get_group("24")
    timing_app_data_SA[16][2] = grouped_timing_data_BH_FP3_0.get_group("23")
    timing_app_data_SA[17][2] = grouped_timing_data_BH_FP3_0.get_group("6")
    timing_app_data_SA[18][2] = grouped_timing_data_BH_FP3_0.get_group("20")
    timing_app_data_SA[19][2] = grouped_timing_data_BH_FP3_0.get_group("47")

    grouped_timing_data_BH_Q_0 = timing_app_data_SA_Q.groupby(timing_app_data_SA_Q.Driver)
    timing_app_data_SA[0][3] = grouped_timing_data_BH_Q_0.get_group("44")
    timing_app_data_SA[1][3] = grouped_timing_data_BH_Q_0.get_group("63")
    timing_app_data_SA[2][3] = grouped_timing_data_BH_Q_0.get_group("1")
    timing_app_data_SA[3][3] = grouped_timing_data_BH_Q_0.get_group("11")
    timing_app_data_SA[4][3] = grouped_timing_data_BH_Q_0.get_group("16")
    timing_app_data_SA[5][3] = grouped_timing_data_BH_Q_0.get_group("55")
    timing_app_data_SA[6][3] = grouped_timing_data_BH_Q_0.get_group("3")
    timing_app_data_SA[7][3] = grouped_timing_data_BH_Q_0.get_group("4")
    timing_app_data_SA[8][3] = grouped_timing_data_BH_Q_0.get_group("14")
    timing_app_data_SA[9][3] = grouped_timing_data_BH_Q_0.get_group("31")
    timing_app_data_SA[10][3] = grouped_timing_data_BH_Q_0.get_group("10")
    timing_app_data_SA[11][3] = grouped_timing_data_BH_Q_0.get_group("22")
    # VET[0] = grouped_timing_data_BH_F1_0.get_group("5")
    timing_app_data_SA[12][3] = grouped_timing_data_BH_Q_0.get_group("27")
    timing_app_data_SA[13][3] = grouped_timing_data_BH_Q_0.get_group("18")
    timing_app_data_SA[14][3] = grouped_timing_data_BH_Q_0.get_group("77")
    timing_app_data_SA[15][3] = grouped_timing_data_BH_Q_0.get_group("24")
    timing_app_data_SA[16][3] = grouped_timing_data_BH_Q_0.get_group("23")
    timing_app_data_SA[17][3] = grouped_timing_data_BH_Q_0.get_group("6")
    timing_app_data_SA[18][3] = grouped_timing_data_BH_Q_0.get_group("20")
    timing_app_data_SA[19][3] = grouped_timing_data_BH_Q_0.get_group("47")

    grouped_timing_data_BH_R_0 = timing_app_data_SA_R.groupby(timing_app_data_SA_R.Driver)
    timing_app_data_SA[0][4] = grouped_timing_data_BH_R_0.get_group("44")
    timing_app_data_SA[1][4] = grouped_timing_data_BH_R_0.get_group("63")
    timing_app_data_SA[2][4] = grouped_timing_data_BH_R_0.get_group("1")
    timing_app_data_SA[3][4] = grouped_timing_data_BH_R_0.get_group("11")
    timing_app_data_SA[4][4] = grouped_timing_data_BH_R_0.get_group("16")
    timing_app_data_SA[5][4] = grouped_timing_data_BH_R_0.get_group("55")
    timing_app_data_SA[6][4] = grouped_timing_data_BH_R_0.get_group("3")
    timing_app_data_SA[7][4] = grouped_timing_data_BH_R_0.get_group("4")
    timing_app_data_SA[8][4] = grouped_timing_data_BH_R_0.get_group("14")
    timing_app_data_SA[9][4] = grouped_timing_data_BH_R_0.get_group("31")
    timing_app_data_SA[10][4] = grouped_timing_data_BH_R_0.get_group("10")
    timing_app_data_SA[11][4] = pd.DataFrame({'condition' : ["DNS"]})
    # VET[0] = grouped_timing_data_BH_F1_0.get_group("5")
    timing_app_data_SA[12][4] = grouped_timing_data_BH_R_0.get_group("27")
    timing_app_data_SA[13][4] = grouped_timing_data_BH_R_0.get_group("18")
    timing_app_data_SA[14][4] = grouped_timing_data_BH_R_0.get_group("77")
    timing_app_data_SA[15][4] = grouped_timing_data_BH_R_0.get_group("24")
    timing_app_data_SA[16][4] = grouped_timing_data_BH_R_0.get_group("23")
    timing_app_data_SA[17][4] = grouped_timing_data_BH_R_0.get_group("6")
    timing_app_data_SA[18][4] = grouped_timing_data_BH_R_0.get_group("20")
    timing_app_data_SA[19][4] = pd.DataFrame({'condition' : ["DNS"]})
    return

def Timing_app_data_SA_Writer():
    i = 0
    timing_app_data_SA[0][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP1_44')
    timing_app_data_SA[1][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP1_63')
    timing_app_data_SA[2][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP1_1')
    timing_app_data_SA[3][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP1_11')
    timing_app_data_SA[4][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP1_16')
    timing_app_data_SA[5][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP1_55')
    timing_app_data_SA[6][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP1_4')
    timing_app_data_SA[7][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP1_3')
    timing_app_data_SA[8][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP1_14')
    timing_app_data_SA[9][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP1_31')
    timing_app_data_SA[10][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP1_10')
    timing_app_data_SA[11][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP1_22')
    timing_app_data_SA[12][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP1_5')
    timing_app_data_SA[13][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP1_18')
    timing_app_data_SA[14][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP1_77')
    timing_app_data_SA[15][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP1_24')
    timing_app_data_SA[16][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP1_23')
    timing_app_data_SA[17][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP1_6')
    timing_app_data_SA[18][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP1_20')
    timing_app_data_SA[19][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP1_47')

    i = 1
    timing_app_data_SA[0][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP2_44')
    timing_app_data_SA[1][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP2_63')
    timing_app_data_SA[2][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP2_1')
    timing_app_data_SA[3][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP2_11')
    timing_app_data_SA[4][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP2_16')
    timing_app_data_SA[5][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP2_55')
    timing_app_data_SA[6][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP2_4')
    timing_app_data_SA[7][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP2_3')
    timing_app_data_SA[8][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP2_14')
    timing_app_data_SA[9][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP2_31')
    timing_app_data_SA[10][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP2_10')
    timing_app_data_SA[11][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP2_22')
    timing_app_data_SA[12][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP2_5')
    timing_app_data_SA[13][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP2_18')
    timing_app_data_SA[14][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP2_77')
    timing_app_data_SA[15][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP2_24')
    timing_app_data_SA[16][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP2_23')
    timing_app_data_SA[17][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP2_6')
    timing_app_data_SA[18][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP2_20')
    timing_app_data_SA[19][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP2_47')

    i = 2
    timing_app_data_SA[0][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP3_44')
    timing_app_data_SA[1][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP3_63')
    timing_app_data_SA[2][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP3_1')
    timing_app_data_SA[3][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP3_11')
    timing_app_data_SA[4][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP3_16')
    timing_app_data_SA[5][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP3_55')
    timing_app_data_SA[6][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP3_4')
    timing_app_data_SA[7][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP3_3')
    timing_app_data_SA[8][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP3_14')
    timing_app_data_SA[9][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP3_31')
    timing_app_data_SA[10][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP3_10')
    timing_app_data_SA[11][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP3_22')
    timing_app_data_SA[12][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP3_5')
    timing_app_data_SA[13][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP3_18')
    timing_app_data_SA[14][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP3_77')
    timing_app_data_SA[15][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP3_24')
    timing_app_data_SA[16][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP3_23')
    timing_app_data_SA[17][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP3_6')
    timing_app_data_SA[18][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP3_20')
    timing_app_data_SA[19][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_FP3_47')

    i = 3
    timing_app_data_SA[0][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_Q_44')
    timing_app_data_SA[1][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_Q_63')
    timing_app_data_SA[2][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_Q_1')
    timing_app_data_SA[3][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_Q_11')
    timing_app_data_SA[4][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_Q_16')
    timing_app_data_SA[5][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_Q_55')
    timing_app_data_SA[6][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_Q_4')
    timing_app_data_SA[7][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_Q_3')
    timing_app_data_SA[8][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_Q_14')
    timing_app_data_SA[9][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_Q_31')
    timing_app_data_SA[10][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_Q_10')
    timing_app_data_SA[11][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_Q_22')
    timing_app_data_SA[12][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_Q_5')
    timing_app_data_SA[13][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_Q_18')
    timing_app_data_SA[14][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_Q_77')
    timing_app_data_SA[15][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_Q_24')
    timing_app_data_SA[16][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_Q_23')
    timing_app_data_SA[17][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_Q_6')
    timing_app_data_SA[18][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_Q_20')
    timing_app_data_SA[19][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_Q_47')

    i = 4
    timing_app_data_SA[0][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_R_44')
    timing_app_data_SA[1][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_R_63')
    timing_app_data_SA[2][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_R_1')
    timing_app_data_SA[3][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_R_11')
    timing_app_data_SA[4][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_R_16')
    timing_app_data_SA[5][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_R_55')
    timing_app_data_SA[6][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_R_4')
    timing_app_data_SA[7][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_R_3')
    timing_app_data_SA[8][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_R_14')
    timing_app_data_SA[9][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_R_31')
    timing_app_data_SA[10][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_R_10')
    timing_app_data_SA[11][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_R_22')
    timing_app_data_SA[12][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_R_5')
    timing_app_data_SA[13][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_R_18')
    timing_app_data_SA[14][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_R_77')
    timing_app_data_SA[15][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_R_24')
    timing_app_data_SA[16][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_R_23')
    timing_app_data_SA[17][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_R_6')
    timing_app_data_SA[18][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_R_20')
    timing_app_data_SA[19][i].to_csv(r'D:\project4_data\SA\timing_app_data_SA_R_47')
    return
#-----------------------------------------------------------------------------------------------------------------------
def Timing_app_data_AU():
    grouped_timing_data_BH_FP1_0 = timing_app_data_AU_FP1.groupby(timing_app_data_AU_FP1.Driver)
    timing_app_data_AU[0][0] = grouped_timing_data_BH_FP1_0.get_group("44")
    timing_app_data_AU[1][0] = grouped_timing_data_BH_FP1_0.get_group("63")
    timing_app_data_AU[2][0] = grouped_timing_data_BH_FP1_0.get_group("1")
    timing_app_data_AU[3][0] = grouped_timing_data_BH_FP1_0.get_group("11")
    timing_app_data_AU[4][0] = grouped_timing_data_BH_FP1_0.get_group("16")
    timing_app_data_AU[5][0] = grouped_timing_data_BH_FP1_0.get_group("55")
    timing_app_data_AU[6][0] = grouped_timing_data_BH_FP1_0.get_group("3")
    timing_app_data_AU[7][0] = grouped_timing_data_BH_FP1_0.get_group("4")
    timing_app_data_AU[8][0] = grouped_timing_data_BH_FP1_0.get_group("14")
    timing_app_data_AU[9][0] = grouped_timing_data_BH_FP1_0.get_group("31")
    timing_app_data_AU[10][0] = grouped_timing_data_BH_FP1_0.get_group("10")
    timing_app_data_AU[11][0] = grouped_timing_data_BH_FP1_0.get_group("22")
    timing_app_data_AU[12][0] = grouped_timing_data_BH_FP1_0.get_group("5")
    timing_app_data_AU[13][0] = grouped_timing_data_BH_FP1_0.get_group("18")
    timing_app_data_AU[14][0] = grouped_timing_data_BH_FP1_0.get_group("77")
    timing_app_data_AU[15][0] = grouped_timing_data_BH_FP1_0.get_group("24")
    timing_app_data_AU[16][0] = grouped_timing_data_BH_FP1_0.get_group("23")
    timing_app_data_AU[17][0] = grouped_timing_data_BH_FP1_0.get_group("6")
    timing_app_data_AU[18][0] = grouped_timing_data_BH_FP1_0.get_group("20")
    timing_app_data_AU[19][0] = grouped_timing_data_BH_FP1_0.get_group("47")

    grouped_timing_data_BH_FP2_0 = timing_app_data_AU_FP2.groupby(timing_app_data_AU_FP2.Driver)
    timing_app_data_AU[0][1] = grouped_timing_data_BH_FP2_0.get_group("44")
    timing_app_data_AU[1][1] = grouped_timing_data_BH_FP2_0.get_group("63")
    timing_app_data_AU[2][1] = grouped_timing_data_BH_FP2_0.get_group("1")
    timing_app_data_AU[3][1] = grouped_timing_data_BH_FP2_0.get_group("11")
    timing_app_data_AU[4][1] = grouped_timing_data_BH_FP2_0.get_group("16")
    timing_app_data_AU[5][1] = grouped_timing_data_BH_FP2_0.get_group("55")
    timing_app_data_AU[6][1] = grouped_timing_data_BH_FP2_0.get_group("3")
    timing_app_data_AU[7][1] = grouped_timing_data_BH_FP2_0.get_group("4")
    timing_app_data_AU[8][1] = grouped_timing_data_BH_FP2_0.get_group("14")
    timing_app_data_AU[9][1] = grouped_timing_data_BH_FP2_0.get_group("31")
    timing_app_data_AU[10][1] = grouped_timing_data_BH_FP2_0.get_group("10")
    timing_app_data_AU[11][1] = grouped_timing_data_BH_FP2_0.get_group("22")
    timing_app_data_AU[12][1] = pd.DataFrame({'condition' : ["DNS"]})
    timing_app_data_AU[13][1] = grouped_timing_data_BH_FP2_0.get_group("18")
    timing_app_data_AU[14][1] = grouped_timing_data_BH_FP2_0.get_group("77")
    timing_app_data_AU[15][1] = grouped_timing_data_BH_FP2_0.get_group("24")
    timing_app_data_AU[16][1] = grouped_timing_data_BH_FP2_0.get_group("23")
    timing_app_data_AU[17][1] = grouped_timing_data_BH_FP2_0.get_group("6")
    timing_app_data_AU[18][1] = grouped_timing_data_BH_FP2_0.get_group("20")
    timing_app_data_AU[19][1] = grouped_timing_data_BH_FP2_0.get_group("47")

    grouped_timing_data_BH_FP3_0 = timing_app_data_AU_FP3.groupby(timing_app_data_AU_FP3.Driver)
    timing_app_data_AU[0][2] = grouped_timing_data_BH_FP3_0.get_group("44")
    timing_app_data_AU[1][2] = grouped_timing_data_BH_FP3_0.get_group("63")
    timing_app_data_AU[2][2] = grouped_timing_data_BH_FP3_0.get_group("1")
    timing_app_data_AU[3][2] = grouped_timing_data_BH_FP3_0.get_group("11")
    timing_app_data_AU[4][2] = grouped_timing_data_BH_FP3_0.get_group("16")
    timing_app_data_AU[5][2] = grouped_timing_data_BH_FP3_0.get_group("55")
    timing_app_data_AU[6][2] = grouped_timing_data_BH_FP3_0.get_group("3")
    timing_app_data_AU[7][2] = grouped_timing_data_BH_FP3_0.get_group("4")
    timing_app_data_AU[8][2] = grouped_timing_data_BH_FP3_0.get_group("14")
    timing_app_data_AU[9][2] = grouped_timing_data_BH_FP3_0.get_group("31")
    timing_app_data_AU[10][2] = grouped_timing_data_BH_FP3_0.get_group("10")
    timing_app_data_AU[11][2] = pd.DataFrame({'condition': ["DNS"]})
    timing_app_data_AU[12][2] = grouped_timing_data_BH_FP3_0.get_group("5")
    timing_app_data_AU[13][2] = grouped_timing_data_BH_FP3_0.get_group("18")
    timing_app_data_AU[14][2] = grouped_timing_data_BH_FP3_0.get_group("77")
    timing_app_data_AU[15][2] = grouped_timing_data_BH_FP3_0.get_group("24")
    timing_app_data_AU[16][2] = grouped_timing_data_BH_FP3_0.get_group("23")
    timing_app_data_AU[17][2] = grouped_timing_data_BH_FP3_0.get_group("6")
    timing_app_data_AU[18][2] = grouped_timing_data_BH_FP3_0.get_group("20")
    timing_app_data_AU[19][2] = grouped_timing_data_BH_FP3_0.get_group("47")

    grouped_timing_data_BH_Q_0 = timing_app_data_AU_Q.groupby(timing_app_data_AU_Q.Driver)
    timing_app_data_AU[0][3] = grouped_timing_data_BH_Q_0.get_group("44")
    timing_app_data_AU[1][3] = grouped_timing_data_BH_Q_0.get_group("63")
    timing_app_data_AU[2][3] = grouped_timing_data_BH_Q_0.get_group("1")
    timing_app_data_AU[3][3] = grouped_timing_data_BH_Q_0.get_group("11")
    timing_app_data_AU[4][3] = grouped_timing_data_BH_Q_0.get_group("16")
    timing_app_data_AU[5][3] = grouped_timing_data_BH_Q_0.get_group("55")
    timing_app_data_AU[6][3] = grouped_timing_data_BH_Q_0.get_group("3")
    timing_app_data_AU[7][3] = grouped_timing_data_BH_Q_0.get_group("4")
    timing_app_data_AU[8][3] = grouped_timing_data_BH_Q_0.get_group("14")
    timing_app_data_AU[9][3] = grouped_timing_data_BH_Q_0.get_group("31")
    timing_app_data_AU[10][3] = grouped_timing_data_BH_Q_0.get_group("10")
    timing_app_data_AU[11][3] = grouped_timing_data_BH_Q_0.get_group("22")
    timing_app_data_AU[12][3] = grouped_timing_data_BH_Q_0.get_group("5")
    timing_app_data_AU[13][3] = grouped_timing_data_BH_Q_0.get_group("18")
    timing_app_data_AU[14][3] = grouped_timing_data_BH_Q_0.get_group("77")
    timing_app_data_AU[15][3] = grouped_timing_data_BH_Q_0.get_group("24")
    timing_app_data_AU[16][3] = grouped_timing_data_BH_Q_0.get_group("23")
    timing_app_data_AU[17][3] = grouped_timing_data_BH_Q_0.get_group("6")
    timing_app_data_AU[18][3] = grouped_timing_data_BH_Q_0.get_group("20")
    timing_app_data_AU[19][3] = grouped_timing_data_BH_Q_0.get_group("47")

    grouped_timing_data_BH_R_0 = timing_app_data_AU_R.groupby(timing_app_data_AU_R.Driver)
    timing_app_data_AU[0][4] = grouped_timing_data_BH_R_0.get_group("44")
    timing_app_data_AU[1][4] = grouped_timing_data_BH_R_0.get_group("63")
    timing_app_data_AU[2][4] = grouped_timing_data_BH_R_0.get_group("1")
    timing_app_data_AU[3][4] = grouped_timing_data_BH_R_0.get_group("11")
    timing_app_data_AU[4][4] = grouped_timing_data_BH_R_0.get_group("16")
    timing_app_data_AU[5][4] = grouped_timing_data_BH_R_0.get_group("55")
    timing_app_data_AU[6][4] = grouped_timing_data_BH_R_0.get_group("3")
    timing_app_data_AU[7][4] = grouped_timing_data_BH_R_0.get_group("4")
    timing_app_data_AU[8][4] = grouped_timing_data_BH_R_0.get_group("14")
    timing_app_data_AU[9][4] = grouped_timing_data_BH_R_0.get_group("31")
    timing_app_data_AU[10][4] = grouped_timing_data_BH_R_0.get_group("10")
    timing_app_data_AU[11][4] = grouped_timing_data_BH_R_0.get_group("22")
    timing_app_data_AU[12][4] = grouped_timing_data_BH_R_0.get_group("5")
    timing_app_data_AU[13][4] = grouped_timing_data_BH_R_0.get_group("18")
    timing_app_data_AU[14][4] = grouped_timing_data_BH_R_0.get_group("77")
    timing_app_data_AU[15][4] = grouped_timing_data_BH_R_0.get_group("24")
    timing_app_data_AU[16][4] = grouped_timing_data_BH_R_0.get_group("23")
    timing_app_data_AU[17][4] = grouped_timing_data_BH_R_0.get_group("6")
    timing_app_data_AU[18][4] = grouped_timing_data_BH_R_0.get_group("20")
    timing_app_data_AU[19][4] = grouped_timing_data_BH_R_0.get_group("47")
    return

def Timing_app_data_AU_Writer():
    i = 0
    timing_app_data_AU[0][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP1_44')
    timing_app_data_AU[1][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP1_63')
    timing_app_data_AU[2][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP1_1')
    timing_app_data_AU[3][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP1_11')
    timing_app_data_AU[4][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP1_16')
    timing_app_data_AU[5][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP1_55')
    timing_app_data_AU[6][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP1_4')
    timing_app_data_AU[7][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP1_3')
    timing_app_data_AU[8][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP1_14')
    timing_app_data_AU[9][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP1_31')
    timing_app_data_AU[10][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP1_10')
    timing_app_data_AU[11][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP1_22')
    timing_app_data_AU[12][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP1_5')
    timing_app_data_AU[13][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP1_18')
    timing_app_data_AU[14][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP1_77')
    timing_app_data_AU[15][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP1_24')
    timing_app_data_AU[16][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP1_23')
    timing_app_data_AU[17][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP1_6')
    timing_app_data_AU[18][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP1_20')
    timing_app_data_AU[19][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP1_47')

    i = 1
    timing_app_data_AU[0][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP2_44')
    timing_app_data_AU[1][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP2_63')
    timing_app_data_AU[2][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP2_1')
    timing_app_data_AU[3][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP2_11')
    timing_app_data_AU[4][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP2_16')
    timing_app_data_AU[5][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP2_55')
    timing_app_data_AU[6][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP2_4')
    timing_app_data_AU[7][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP2_3')
    timing_app_data_AU[8][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP2_14')
    timing_app_data_AU[9][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP2_31')
    timing_app_data_AU[10][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP2_10')
    timing_app_data_AU[11][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP2_22')
    timing_app_data_AU[12][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP2_5')
    timing_app_data_AU[13][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP2_18')
    timing_app_data_AU[14][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP2_77')
    timing_app_data_AU[15][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP2_24')
    timing_app_data_AU[16][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP2_23')
    timing_app_data_AU[17][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP2_6')
    timing_app_data_AU[18][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP2_20')
    timing_app_data_AU[19][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP2_47')

    i = 2
    timing_app_data_AU[0][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP3_44')
    timing_app_data_AU[1][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP3_63')
    timing_app_data_AU[2][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP3_1')
    timing_app_data_AU[3][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP3_11')
    timing_app_data_AU[4][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP3_16')
    timing_app_data_AU[5][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP3_55')
    timing_app_data_AU[6][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP3_4')
    timing_app_data_AU[7][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP3_3')
    timing_app_data_AU[8][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP3_14')
    timing_app_data_AU[9][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP3_31')
    timing_app_data_AU[10][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP3_10')
    timing_app_data_AU[11][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP3_22')
    timing_app_data_AU[12][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP3_5')
    timing_app_data_AU[13][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP3_18')
    timing_app_data_AU[14][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP3_77')
    timing_app_data_AU[15][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP3_24')
    timing_app_data_AU[16][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP3_23')
    timing_app_data_AU[17][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP3_6')
    timing_app_data_AU[18][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP3_20')
    timing_app_data_AU[19][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_FP3_47')

    i = 3
    timing_app_data_AU[0][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_Q_44')
    timing_app_data_AU[1][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_Q_63')
    timing_app_data_AU[2][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_Q_1')
    timing_app_data_AU[3][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_Q_11')
    timing_app_data_AU[4][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_Q_16')
    timing_app_data_AU[5][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_Q_55')
    timing_app_data_AU[6][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_Q_4')
    timing_app_data_AU[7][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_Q_3')
    timing_app_data_AU[8][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_Q_14')
    timing_app_data_AU[9][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_Q_31')
    timing_app_data_AU[10][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_Q_10')
    timing_app_data_AU[11][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_Q_22')
    timing_app_data_AU[12][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_Q_5')
    timing_app_data_AU[13][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_Q_18')
    timing_app_data_AU[14][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_Q_77')
    timing_app_data_AU[15][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_Q_24')
    timing_app_data_AU[16][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_Q_23')
    timing_app_data_AU[17][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_Q_6')
    timing_app_data_AU[18][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_Q_20')
    timing_app_data_AU[19][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_Q_47')

    i = 4
    timing_app_data_AU[0][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_R_44')
    timing_app_data_AU[1][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_R_63')
    timing_app_data_AU[2][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_R_1')
    timing_app_data_AU[3][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_R_11')
    timing_app_data_AU[4][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_R_16')
    timing_app_data_AU[5][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_R_55')
    timing_app_data_AU[6][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_R_4')
    timing_app_data_AU[7][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_R_3')
    timing_app_data_AU[8][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_R_14')
    timing_app_data_AU[9][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_R_31')
    timing_app_data_AU[10][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_R_10')
    timing_app_data_AU[11][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_R_22')
    timing_app_data_AU[12][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_R_5')
    timing_app_data_AU[13][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_R_18')
    timing_app_data_AU[14][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_R_77')
    timing_app_data_AU[15][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_R_24')
    timing_app_data_AU[16][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_R_23')
    timing_app_data_AU[17][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_R_6')
    timing_app_data_AU[18][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_R_20')
    timing_app_data_AU[19][i].to_csv(r'D:\project4_data\AU\timing_app_data_AU_R_47')
    return
#-----------------------------------------------------------------------------------------------------------------------
def main():
    #the function names are timing_data_BH_O as "oh"
    #and timing_data_BH_I as the upper case of "i"
    #this is because otherwise the function name is
    #the same as the list name
    #and causes the error below:
    #TypeError: 'function' object is not subscriptable
    #print(car_data_BH_FP1['1']) = the car data set for max verstappen in python dataframe
    #print(type(car_data_BH_FP1['1'])) = python data frame
    #Timing_app_data_BH()
    #Timing_app_data_BH_Writer()

    #Timing_app_data_SA()
    #Timing_app_data_SA_Writer()

    #Timing_app_data_AU()
    #Timing_app_data_AU_Writer()
    #print(type(timing_app_data_BH_FP1))
    #print(timing_app_data_BH_FP1)
    print("done")
    return
#-----------------------------------------------------------------------------------------------------------------------
if __name__ == "__main__":
    main()